CREATE TABLE `crawler_score` (
	`no_index` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`insertedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '데이터입력시간',
	`origin_ph` VARCHAR(255) NULL DEFAULT NULL COMMENT 'SCI에서 받은 리스트에 기입되었던 핸드폰 번호',
	`platform` VARCHAR(255) NULL DEFAULT NULL COMMENT '정보를 가져오는 플랫폼',
	`page_id` VARCHAR(255) NULL DEFAULT NULL COMMENT '해당 플랫폼의 사용자 페이지 아이디',
	`username` VARCHAR(255) NULL DEFAULT NULL COMMENT '사용자 이름',
	`gender` VARCHAR(255) NULL DEFAULT NULL COMMENT '사용자 성별',
	`phone_number` VARCHAR(255) NULL DEFAULT NULL COMMENT '해당 플랫폼에 노출된 사용자 전화번호',
	`birthday` VARCHAR(255) NULL DEFAULT NULL COMMENT '사용자 생일',
	`address1` VARCHAR(255) NULL DEFAULT NULL COMMENT '사용자 주소 히스토리1(노출되는 정보에 따라 다른데; 1번이 거주지일수도 있고; 출신지일 수도 있음-공개 정도에 따라 노출되는 정보의 종류가 다름)',
	`address2` VARCHAR(255) NULL DEFAULT NULL COMMENT '사용자 주소 히스토리2(노출되는 정보에 따라 다른데; 2번이 거주지일수도 있고; 출신지일 수도 있음-공개 정도에 따라 노출되는 정보의 종류가 다름)',
	`address3` VARCHAR(255) NULL DEFAULT NULL COMMENT '사용자 주소 히스토리3(노출되는 정보에 따라 다른데; 3번이 거주지일수도 있고; 출신지일 수도 있음-공개 정도에 따라 노출되는 정보의 종류가 다름)',
	`company1` VARCHAR(255) NULL DEFAULT NULL COMMENT '사용자 직장 히스토리1(노출되는 정보의 양에 따라 과거 직장 정보일 수도 있고; 현재 직장 정보일 수도 있음)',
	`company2` VARCHAR(255) NULL DEFAULT NULL COMMENT '사용자 직장 히스토리2(노출되는 정보의 양에 따라 과거 직장 정보일 수도 있고; 현재 직장 정보일 수도 있음)',
	`company3` VARCHAR(255) NULL DEFAULT NULL COMMENT '사용자 직장 히스토리3(노출되는 정보의 양에 따라 과거 직장 정보일 수도 있고; 현재 직장 정보일 수도 있음)',
	`university1` VARCHAR(255) NULL DEFAULT NULL COMMENT '사용자 학력 히스토리1(노출되는 정보의 양에 따라 고등학교 정보일 수도 있고; 대학 정보; 대학원 정보 일 수도 있음)',
	`university2` VARCHAR(255) NULL DEFAULT NULL COMMENT '사용자 학력 히스토리2(노출되는 정보의 양에 따라 고등학교 정보일 수도 있고; 대학 정보; 대학원 정보 일 수도 있음)',
	`university3` VARCHAR(255) NULL DEFAULT NULL COMMENT '사용자 학력 히스토리3(노출되는 정보의 양에 따라 고등학교 정보일 수도 있고; 대학 정보; 대학원 정보 일 수도 있음)',
	`contact1` VARCHAR(255) NULL DEFAULT NULL COMMENT '사용자 추가 SNS 주소 정보 1',
	`contact2` VARCHAR(255) NULL DEFAULT NULL COMMENT '사용자 추가 SNS 주소 정보 2',
	`expression_negative` VARCHAR(255) NULL DEFAULT NULL COMMENT '부정표현 비율',
	`expression_positive` VARCHAR(255) NULL DEFAULT NULL COMMENT '긍정표현 비율',
	`friends_all` VARCHAR(255) NULL DEFAULT NULL COMMENT '모든 친구 수',
	`friends_residence` VARCHAR(255) NULL DEFAULT NULL COMMENT '거주지 친구 수',
	`friends_company` VARCHAR(255) NULL DEFAULT NULL COMMENT '직장 친구 수',
	`friends_univ` VARCHAR(255) NULL DEFAULT NULL COMMENT '대학교 친구 수',
	`friends_highschool` VARCHAR(255) NULL DEFAULT NULL COMMENT '고등학교 친구 수',
	`friends_native` VARCHAR(255) NULL DEFAULT NULL COMMENT '출신지 친구 수',
	`take_news` VARCHAR(255) NULL DEFAULT NULL COMMENT '소식 받는 수(카카오)',
	`post_interest` VARCHAR(255) NULL DEFAULT NULL COMMENT '관심글 수(카카오)',
	`post_up` VARCHAR(255) NULL DEFAULT NULL COMMENT 'UP 한 글 수(카카오)',
	`feeling_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '느낌 글 수(카카오)',
	`following_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '팔로잉 수',
	`follower_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '팔로워 수',
	`like_all_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '정보 탭에서의 좋아요에 해당하는 항목 전체의 수(페이스북)',
	`like_movie_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '공개된 영화 좋아요 수',
	`like_tv_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '공개된 TV 좋아요 수',
	`like_music_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '공개된 음악 좋아요 수',
	`like_book_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '공개된 책 좋아요 수',
	`like_sports_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '공개된 스포츠 좋아요 수',
	`like_athlete_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '공개된 운동선수 좋아요 수',
	`like_restaurant_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '공개된 음식점 좋아요 수',
	`like_appgame_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '공개된 앱/게임 좋아요 수',
	`check_in` VARCHAR(255) NULL DEFAULT NULL COMMENT '체크인 수',
	`event` VARCHAR(255) NULL DEFAULT NULL COMMENT '이벤트 수',
	`review` VARCHAR(255) NULL DEFAULT NULL COMMENT '리뷰 수',
	`like_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '게시글의 좋아요 표시 수',
	`comment_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '게시글의 댓글 수',
	`share_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '게시글의 공유 수',
	`place_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '장소 수',
	`place_add` VARCHAR(255) NULL DEFAULT NULL COMMENT '장소 추가 수',
	`post_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '전체 게시글 수',
	`photo_of_oneself_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '해당 사용자가 나온 사진 수',
	`photo_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '전체 사진 개수',
	`album_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '앨범 전체 개수',
	`album_category_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '앨범 카테고리 수',
	`video_tag_oneself_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '해당 사용자가 테그된 동영상 수',
	`video_cnt` VARCHAR(255) NULL DEFAULT NULL COMMENT '동영상 전체 개수',
	`operation_year_period` VARCHAR(255) NULL DEFAULT NULL COMMENT '운영 년도 수',
	`friends_continuous_exchange` VARCHAR(255) NULL DEFAULT NULL COMMENT '친한 친구와의 지속적인 교류 정도',
	`friends_rating_index` VARCHAR(255) NULL DEFAULT NULL COMMENT '친구의 전체적인 평가 정도',
	`friends_correlation_score` VARCHAR(255) NULL DEFAULT NULL COMMENT '친구별 상관도 정도',
	`contents_regular` VARCHAR(255) NULL DEFAULT NULL COMMENT '컨텐츠 관리의 일정성',
	PRIMARY KEY (`no_index`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
