CREATE TABLE `SCI_2nd_HanaCaptial_RateTable` (
	`index` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`userName` VARCHAR(50) NULL DEFAULT NULL,
	`userCellPhoneNumber` VARCHAR(100) NULL DEFAULT NULL,
	`1st_Test_T` VARCHAR(50) NULL DEFAULT NULL,
	`1st_Test_C` VARCHAR(50) NULL DEFAULT NULL,
	`1st_Test_M` VARCHAR(50) NULL DEFAULT NULL,
	`1st_Test_RATE` VARCHAR(50) NULL DEFAULT NULL,
	`2nd_Test_T` VARCHAR(50) NULL DEFAULT NULL,
	`2nd_Test_C` VARCHAR(50) NULL DEFAULT NULL,
	`2nd_Test_M` VARCHAR(50) NULL DEFAULT NULL,
	`2nd_Test_RATE` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`index`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
